LeaveMngment/Controllers/UserLeaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LeaveMngment.Common;
using LeaveMngment.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace LeaveMngment.Controllers
{
    public class UserLeaveController : Controller
    {
        private LeaveManagementContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserLeaveController(LeaveManagementContext db, IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index(string currentFilter, string Status, string search, int? page)
        {
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;
            var usr = _db.AspNetUsers.OrderByDescending(x => x.UserName).FirstOrDefault(x => x.UserName == userId);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var leave_days = _db.UserLeaveDays.ToList();
            if (usr.Title == "HR")
            {
                
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search)).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Department.StartsWith(search)).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                return View(leave_days.ToPagedList(pageNumber, 25));
            }
            if (usr.Title == "Manager")
            {
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.Department == usr.Department).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Department.StartsWith(search) && s.Department == usr.Department).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                leave_days = leave_days.Where(s => s.UserName == userId).ToList();
                return View(leave_days.ToPagedList(pageNumber, 25));
            }
            if (usr.Title == "Employee")
            {
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.UserName == userId).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Department.StartsWith(search) && s.UserName == userId).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                leave_days = leave_days.Where(s => s.UserName == userId).ToList();
                return View(leave_days.ToPagedList(pageNumber, 25));
            }
            return View();
            
        }
        public IActionResult ScheduleIndex(string currentFilter, string Status, string search, int? page)
        {
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;

            var usr = _db.AspNetUsers.OrderByDescending(x => x.UserName).FirstOrDefault(x => x.UserName == userId);
            if(usr.Title == "HR")
            {
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                var leave_days = _db.UserLeaveDays.ToList();
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.LeaveType == "Annual").ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.LeaveType == "Annual").ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                leave_days = leave_days.Where(s=>s.LeaveType == "Annual").ToList();
                var lDayss = leave_days.ToPagedList(pageNumber, 25);
                return View(lDayss);
            }
            if(usr.Title == "Manager")
            {
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                var leave_days = _db.UserLeaveDays.ToList();
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.LeaveType == "Annual" && s.Department == usr.Department).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Department.StartsWith(search) && s.LeaveType == "Annual" && s.Department == usr.Department).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }

                leave_days = leave_days.Where(s => s.LeaveType == "Annual" && s.Department == usr.Department).ToList();
                var lDayss = leave_days.ToPagedList(pageNumber, 25);
                return View(lDayss);
            }
            if (usr.Title == "Employee")
            {
                int pageSize = 10;
                int pageNumber = (page ?? 1);
                var leave_days = _db.UserLeaveDays.ToList();
                if (Status == "Email")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.LeaveType == "Annual" && s.UserName == userId).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                if (Status == "Department")
                {
                    leave_days = leave_days.Where(s => s.Email.StartsWith(search) && s.LeaveType == "Annual" && s.UserName == userId).ToList();
                    var lDays = leave_days.ToPagedList(pageNumber, 25);
                    return View(lDays);
                }
                leave_days = leave_days.Where(s => s.LeaveType == "Annual" && s.UserName == userId).ToList();
                var lDayss = leave_days.ToPagedList(pageNumber, 25);
                return View(lDayss);
            }
            return View();
        }
        //view schedule
        public IActionResult ViewSchedule()
        {
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;
            var usr = _db.AspNetUsers.OrderByDescending(x => x.UserName).FirstOrDefault(x => x.UserName == userId);
            if (usr.Title == "HR")
            {
                var schedule = _db.LeaveSchedule.Where(x => x.Status == 1).ToList();
                return View(schedule);
            }
            if (usr.Title == "Manager")
            {
                var schedule = _db.LeaveSchedule.Where(x => x.Status == 1 && x.Department == usr.Department).ToList();
                return View(schedule);
            }
            return View();
        }
        public IActionResult CreateSchedule(int id)
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSchedule(int id, LeaveSchedule leaveSchedule)
        {
            var lDays = _db.UserLeaveDays.OrderByDescending(x => x.Id).FirstOrDefault(x => x.Id == id);
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;

            var usr = _db.AspNetUsers.OrderByDescending(x => x.UserName).FirstOrDefault(x => x.UserName == userId);
            if (usr.Title == "HR")
            {
                LeaveSchedule leave = new LeaveSchedule();
                leave.LeaveFrom = leaveSchedule.LeaveFrom;
                leave.LeaveTo = leaveSchedule.LeaveTo;
                leave.Days = leaveSchedule.Days;
                leave.Department = lDays.Department;
                leave.Email = lDays.Email;
                leave.Status =(int) MyEnums.StatusOption.Added;
                leave.Maker = usr.UserName;
                _db.LeaveSchedule.Add(leave);
                _db.SaveChanges();
                TempData["successmessage"] = "Schedule Created successfully";
                return RedirectToAction("ViewSchedule");
            }
            if(usr.Title == "Manager")
            {
                LeaveSchedule leave = new LeaveSchedule();
                leave.LeaveFrom = leaveSchedule.LeaveFrom;
                leave.LeaveTo = leaveSchedule.LeaveTo;
                leave.Days = leaveSchedule.Days;
                leave.Department = lDays.Department;
                leave.Email = lDays.Email;
                leave.Status = (int)MyEnums.StatusOption.Added;
                leave.Maker = usr.UserName;
                _db.LeaveSchedule.Add(leave);
                _db.SaveChanges();
                TempData["successmessage"] = "Schedule Created successfully";
                return RedirectToAction("ViewSchedule");
            }
            return View();
        }
        public IActionResult ViewUpproved()
        {
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;

LeaveMngment/Views/UserLeave/CreateSchedule.cshtml
@model LeaveMngment.Models.LeaveSchedule

@{
    ViewData["Title"] = "CreateSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
<hr />
<div class="panel panel-success">
    <div class="panel-heading">Create New Schedule</div>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="CreateSchedule">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group" style="margin-left: 10px">
                    <label asp-for="LeaveFrom" class="control-label"></label>
                    <input asp-for="LeaveFrom" type="date" class="form-control" />
                    <span asp-validation-for="LeaveFrom" class="text-danger"></span>
                </div>
                <div class="form-group" style="margin-left: 10px">
                    <label asp-for="LeaveTo" class="control-label"></label>
                    <input asp-for="LeaveTo" type="date" class="form-control" />
                    <span asp-validation-for="LeaveTo" class="text-danger"></span>
                </div>
                <div class="form-group" style="margin-left: 10px">
                    <label asp-for="Days" class="control-label"></label>
                    <input asp-for="Days" class="form-control" />
                    <span asp-validation-for="Days" class="text-danger"></span>
                </div>
                <div class="form-group" style="margin-left: 10px">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div class="panel-footer">
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

LeaveMngment/Views/UserLeave/Index.cshtml
@model IPagedList<LeaveMngment.Models.UserLeaveDays>
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Index", "UserLeave", FormMethod.Get))
        {
            @Html.DropDownList("Status", new List<SelectListItem>

            {
                new SelectListItem {Text = "Email", Value = "Email"},
                new SelectListItem {Text = "Department", Value = "Department"},
            }, new { @class = "form-control", style = "width:333px" })
            <br />
            @Html.TextBox("Search", null, new { @class = "form-control", style = "width:333px" })
            <br />
            <input type="submit" class="btn btn-success" value="Search">
        }
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                User Name
            </th>
            <th>
                Email
            </th>
            <th>
                Department
            </th>
            <th>
                Leave Type
            </th>
            <th>
                Actual Leave Days
            </th>
            <th>
                Remaining Days
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RemainingDays)
                </td>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

LeaveMngment/Views/UserLeave/ScheduleIndex.cshtml
@model IPagedList<LeaveMngment.Models.UserLeaveDays>
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="/Content/PagedList.css" rel="stylesheet" type="text/css" />

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("ScheduleIndex", "UserLeave", FormMethod.Get))
        {
            @Html.DropDownList("Status", new List<SelectListItem>

            {
                new SelectListItem {Text = "Email", Value = "Email"},
                new SelectListItem {Text = "Department", Value = "Department"},
            }, new { @class = "form-control", style = "width:333px" })
            <br />
            @Html.TextBox("Search", null, new { @class = "form-control", style = "width:333px" })
            <br />
            <input type="submit" class="btn btn-success" value="Search">
        }
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                User Name
            </th>
            <th>
                Email
            </th>
            <th>
                Department
            </th>
            <th>
                Leave Type
            </th>
            <th>
                Actual Leave Days
            </th>
            <th>
                Remaining Days
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RemainingDays)
                </td>
                <td>
                    <a asp-action="CreateSchedule" asp-route-id="@item.Id">Create Leave chedule</a>
                </td>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

LeaveMngment/Views/UserLeave/ViewApproved.cshtml
@model IEnumerable<LeaveMngment.Models.LeaveSchedule>

@{
    ViewData["Title"] = "ViewSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<hr />
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>
                Leave From
            </th>
            <th>
                Leave To
            </th>
            <th>
                Department
            </th>
            <th>
                Email
            </th>
            <th>
                Days
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Days)
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>

LeaveMngment/Views/UserLeave/ViewRejected.cshtml
@model IEnumerable<LeaveMngment.Models.LeaveSchedule>

@{
    ViewData["Title"] = "ViewSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<hr />
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>
                Leave From
            </th>
            <th>
                Leave To
            </th>
            <th>
                Department
            </th>
            <th>
                Email
            </th>
            <th>
                Days
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Days)
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>

LeaveMngment/Views/UserLeave/ViewSchedule.cshtml
@model IEnumerable<LeaveMngment.Models.LeaveSchedule>

@{
    ViewData["Title"] = "ViewSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<hr />
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>
                Leave From
            </th>
            <th>
                Leave To 
            </th>
            <th>
                Department
            </th>
            <th>
                Email
            </th>
            <th>
                Days
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Days)
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>

LeaveMngment/Views/UserLeave/ViewUnaproved.cshtml
@model IEnumerable<LeaveMngment.Models.LeaveSchedule>

@{
    ViewData["Title"] = "ViewSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<hr />
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>
                Leave From
            </th>
            <th>
                Leave To
            </th>
            <th>
                Department
            </th>
            <th>
                Email
            </th>
            <th>
                Days
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveTo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Days)
                </td>
                <td>
                    <a asp-action="Reject" asp-route-id="@item.Id">Reject</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>

LeaveMngment/Views/UserLeave/ViewUpproved.cshtml
@model IEnumerable<LeaveMngment.Models.LeaveSchedule>

@{
    ViewData["Title"] = "ViewSchedule";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
<hr />
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

    <thead>
        <tr>
            <th>
                Leave From
            </th>
            <th>
                Leave To
            </th>
            <th>
                Department
            </th>
            <th>
                Email
            </th>
            <th>
                Days
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Days)
            </td>
            <td>
                <a asp-action="Approve" asp-route-id="@item.Id">Approve</a> |
            </td>
        </tr>
        }
    </tbody>
</table>
<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
<script>
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#example').DataTable();
    });
    // Code that uses other library's $ can follow here.
</script>
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>